### ISSUE TITLE
xss attack

### ISSUE THREAD

**Issue by petarov** [kidGodzilla/Chattr#3]
I was browsing the F7 demos only to find out that this one has been XSS hacked. From what I saw in my chrome dev tools, it seems to come from malicious messages saved in the firebase database.

Please have a look on this!

**Comment by nolimits4web** [comment]
Base cleaned

**Comment by kidGodzilla** [comment]
Thanks!

**Comment by praneybehl** [comment]
Its back again. Alerts loop infinitely. Can someone please confirm? Needs to be fixed. 
Thanks
